### ISSUE TITLE
Height does not update when options are appended to list

### ISSUE THREAD

**Issue by JeffJassky** [wan2land/vue-scroll-picker#11]
In the case of `<ScrollPicker :options="options" />` the initial render works correctly. If a new option is added anywhere in `options` it gets correctly appended in the dom, but the last-most option will no longer be selectable.

An `options` watcher should trigger a recalculation of the layout.

**Comment by wan2land** [comment]
Example, https://wani.kr/vue-scroll-picker/#/example-dynamic-options
