### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by kovinet** [wan2land/vue-scroll-picker#206]
Are there any plans to port this library to work with Vue 3?

**Comment by wan2land** [comment]
Work is in progress. It takes about a week. :smile: 

See [https://github.com/wan2land/vue-scroll-picker/tree/1.0.0](https://github.com/wan2land/vue-scroll-picker/tree/1.0.0)

**Comment by wan2land** [comment]
v1.0.0 released. 🎉  try it!
