### ISSUE TITLE
After change to Vue3 top css property in vue-scroll-picker-rotator no longer reactive

### ISSUE THREAD

**Issue by habos** [wan2land/vue-scroll-picker#292]
I had added custom css to the scroll picker so that it was larger then the ones in the demo which worked in Vue2 because your top property would adjust for text size.  Now the top property remains constant no matter what I change in the css.  Not really an issue, just sad that I will no longer be able to use this component.

**Comment by wan2land** [comment]
https://vue-scroll-picker.dist.be/#reactive_style

Is this the function you want?  If yes, use `v1.1.0`. 😆
