### ISSUE TITLE
Not working inside bootstrap 3 modal

### ISSUE THREAD

**Issue by HeriBrito** [wan2land/vue-scroll-picker#3]
Hi wan2land,

i've tried to use your amazing component in my application, but not luck using it inside a modal bootstrap 3. The component render ok, show the list and make the scroll, but when release de wheel ... always go top:0px. When use the component outside the modal, all it's ok.

Is there any fix so i can use it inside the modal?. Sorry, i'm experiencied vue programmer, but my know of css is very limited :(

Thank you for all,
Heri

**Comment by HeriBrito** [comment]
Opps ... sorrry. The modal component i'm using is from UIV

**Comment by HeriBrito** [comment]
... and this is the code snipet:

`<modal v-model="modalTime" size="sm" :header="false" :backdrop="false">
          <h3 style="text-align: center; position: relative;top: 10px;">Set Countdown</h3>
          <div style="font-size: 20px;">
              <scroll-picker-group class="flex">
                  <scroll-picker :options="horas" v-model="horaTime"></scroll-picker>
                  <scroll-picker :options="minutos" v-model="minTime"></scroll-picker>
              </scroll-picker-group>
          </div>
          <div slot="footer">
              <btn @click="timerSetted" type="danger">Ok</btn>
          </div>
      </modal>`

... thxs again !!

**Comment by wan2land** [comment]
I found where it was a bug. I'll put up a revised version soon!

**Comment by wan2land** [comment]
It seems to be a conflict with Modal in the UIV package.
Next time, I would like to be able to write down exactly what library you are using, not the bootstrap! @HeriBrito

**Comment by webnoob** [comment]
Any news on this? I'm also having the same issue using your component alongside Vue Quasars modal component - although it's intermittent. Sometimes, it works and other times not ...

**Comment by webnoob** [comment]
I'll give it a shot. Thanks for your time on this - it's the only component for Vue doing this and I didn't want to roll my own :)
