### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by Droutin** [wan2land/vue-scroll-picker#387]
Hello,

Is there option to render multiple column picker? Something like this 
![image](https://user-images.githubusercontent.com/17362753/133108296-6900cf54-f312-4c4b-8c64-c9a088e78fd1.png)
I need it for days, months & years

**Comment by wan2land** [comment]
you can use flex! I made a simple date picker for you. :-)

https://vue-scroll-picker.dist.be/#multiple
https://github.com/wan2land/vue-scroll-picker/blob/main/example/ExampleMultiple.vue
