### ISSUE TITLE
Doesn't work inside <transition>

### ISSUE THREAD

**Issue by stylefieber** [wan2land/vue-scroll-picker#4]
When inside of a transition (<transition>) then scroll-picker does not work. When you scroll it just jumps back to top.

**Comment by stylefieber** [comment]
temporary and hacky workaround is to enable it after the animation is finished

**Comment by wan2land** [comment]
can i see the source? :-)

**Comment by wan2land** [comment]
i have created a transition example. check it please! :-)

http://wani.kr/vue-scroll-picker/#/example-transition
