### ISSUE TITLE
Making it clickable, and embedding on a Carrd website?

### ISSUE THREAD

**Issue by w4rner** [wan2land/vue-scroll-picker#446]
I'm interested in the [Single view](https://github.com/wan2land/vue-scroll-picker/blob/main/example/Example.vue).

1). I wanna make it so that it goes to the website depending on which subdomain the user scroll picks, as follows:

![2021-10-27 18 16 43](https://user-images.githubusercontent.com/31451410/139114606-313225aa-e2d0-427d-9f38-93f547cd61f0.png)

e.g. here it should go to wa.rner.me
If a separate Go button won't work, maybe I could make the scroll option text itself clickable?

2). I need to embed this is as self-contained HTML embed on a Carrd website.
There's a lot of import from relative files like 
`import ExampleDynamicOptions from './ExampleDynamicOptions.vue'`

Is it possible to assemble a single HTML file which packages everything you need (like [my Accordion](https://github.com/w4rner/moderner/tree/main/Accordion) which uses Vue JS)?

**Comment by wan2land** [comment]
Forgive me for being late. 🙏🙏

I forgot to check it out now. Is this still a valid issue?

**Comment by wan2land** [comment]
If you are using vue2, see the following readme. Previous versions(0.x) provided build files for use on the web.

[https://github.com/wan2land/vue-scroll-picker/tree/0.x-vue2](https://github.com/wan2land/vue-scroll-picker/tree/0.x-vue2)

vue-scroll-picker 1.x no longer provides the above method. but, it's possible with modules.

[https://javascript.info/modules-intro](https://javascript.info/modules-intro)

All npm packages are available through [esm.sh](https://esm.sh).

```
<script type="module">
import * as Vue from "https://esm.sh/vue@3.2.31"
import VueScrollPicker from "https://esm.sh/vue-scroll-picker@1.1.1"
</script>
```

**Comment by w4rner** [comment]
Not sure if I'm 'using' vue2. I'm tryna embed an HTML segment in a Carrd.co profile.

would trying the 'global' HTML code be a good place to start:
[image.png]

------- Original Message -------
