### ISSUE TITLE
Rotator initial position not correct with initial option of zero

### ISSUE THREAD

**Issue by jettway** [wan2land/vue-scroll-picker#5]
My options are  `[0,1,2]`. I set the initial value to 0, using either `:value` or `v-model`. The value is correctly stored inside the vue-scroll-picker component, but the rotator does not put the diplayed zero in the correct middle position on screen. (Instead is stays below until you interact with it.) I can fix this issue by calling `correctionAfterDragging()` when the component is mounted.

**Comment by wan2land** [comment]
I'll check. Can I see the source code? 😃

**Comment by JeffJassky** [comment]
Having the same issue.

**Comment by wan2land** [comment]
Fixed in v0.4.1
