### ISSUE TITLE
Scroller's selectedValue skips to 0th element if I scroll too far in the list

### ISSUE THREAD

**Issue by SuharshTyagii** [wan2land/vue-scroll-picker#549]
The scroller skips to top (0th element) if I try to scroll further than the last element, with a mouse. Please help?

**Comment by wan2land** [comment]
I'll fix it soon! :smile:

**Comment by wan2land** [comment]
try v1.1.2 🙃

**Comment by SuharshTyagii** [comment]
Nice work man, you actually fixed it, thanks!!
