### ISSUE TITLE
Missing `lib/vue-scroll-picker.es.js`

### ISSUE THREAD

**Issue by sheldonbaker** [wan2land/vue-scroll-picker#553]
I'm getting errors from vite: `Failed to resolve entry for package "vue-scroll-picker"...The package may have incorrect main/module/exports specified in its package.json`

It looks like it's because the `module` file definition in `package.json` points to a file that is non-existent for me: `lib/vue-scroll-picker.es.js`. (There is only `lib/vue-scroll-picker.mjs.js` and `lib/vue-scroll-picker.umd.js`.) 

Using node v16.17.1.

**Comment by wan2land** [comment]
Oops.. 😱
fixed in v1.1.3! Try it 🤗
