### ISSUE TITLE
Feature request: Reduce height - only show one faded item above and below?

### ISSUE THREAD

**Issue by andrewj-bjss** [wan2land/vue-scroll-picker#6]
I'd like to reduce the height of the scroller, and show only 3 items in the scroll, the selected one, and one above and one below.  

so:

2
**3**
4

and not

1
2
**3**
4
5

I think I need to set css for .vue-scroll-picker and .vue-scroll-picker-layer > .bottom .top .middle, etc. Some combination of  height/bottom/top values?

Does this make sense?

**Comment by wan2land** [comment]
I think there are a lot of changes. I will try to improve together in the future. Thank you for your issue.

**Comment by plusone-masaki** [comment]
With virtual scrolling, I know a good solution.
Why don't you introduce the following library?
https://github.com/Akryum/vue-virtual-scroller

**Comment by wan2land** [comment]
```vue

<style>
.example .vue-scroll-picker {
  height: 6em; /* default 10em */
}
</style>
<template>
  <div class="example">
    <scroll-picker :options="options" />
  </div>
</template>
```

I modified the CSS a bit. You can change the height more easily. You only need to modify the height of the `vue-scroll-picker`.
