### ISSUE TITLE
BUG: VueScrollPicker doesn't allow text highlighting in the page that it exists!!

### ISSUE THREAD

**Issue by zifnab87** [wan2land/vue-scroll-picker#797]
please try text highlighting anything in the examples page https://vue-scroll-picker.dist.be/ and you will see that it doesn't work.. Not sure why it does preventDefault in all those events even outside of its area..

Thanks!

**Comment by wan2land** [comment]
fix v1.1.4

**Comment by zifnab87** [comment]
wow thanks!!! so quick!
