### ISSUE TITLE
Coordinate shifts when options depend on value.

### ISSUE THREAD

**Issue by plusone-masaki** [wan2land/vue-scroll-picker#81]
I am trying to create a TimePicker.
The options of the number of days fluctuate according to the value of month, but when you scroll the date and time, the coordinates are shifted and the selector penetrates far upward.

Fortunately, I read the library source and found out why and how to fix it.
Cause: calculatePivots and onScroll are running at the same time.
Solved Solution: Delay $ emit () in correction method.

I will send you a pull request as soon as verification is completed, so please merge it.

**Comment by plusone-masaki** [comment]
Right now, I've confirmed that all the demos work correctly, so I sent a PR.
After confirmation, please merge.

https://github.com/wan2land/vue-scroll-picker/pull/86

**Comment by wan2land** [comment]
Merged. :-)
Tomorrow(Korea time UTC+09:00), It will be released as v0.4.0 with #11
