### ISSUE TITLE
Suggest item disable property

### ISSUE THREAD

**Issue by KumJungMin** [wan2land/vue-scroll-picker#816]
### Suggest
- I suggest `disable` property to prevent scrolling on some item. 
- If disabled item is selected, scrolling next item.
- disabled item movement is similar as date picker spinner of android.

<br/>

> direction 1, add disable property on options item

Name | Type | Default | Example
-- | -- | -- | --
... | ... | ... |  ...
options | string[]{ name: string, value: any, **disabled?: boolean** }[] | [] | `["10KG", "20KG", "30KG"]`, `[{value: 10, name: "10KG", disabled: true }`, `{value: 20, name: "20KG"}`]

<br/>

> direction 2, add isDisabled on props

- isDisabled Returns if an individual option item is enabled or disabled. If false, the item will be inactive

Name | Type | Default | Example
-- | -- | -- | --
... | ... | ... |  ...
**isDisabled** | **(option:{ name: string, value: any }) => boolean), boolean** | **false** | `({ name, value }) => value > 2`, `true`

**Comment by wan2land** [comment]
🤔

**Comment by wan2land** [comment]
I've implemented the feature following the first suggestion, but there are significant changes, so I plan to release it after extensive testing. Please bear with me for a bit. 😊

**Comment by KumJungMin** [comment]
thank you for positive comment :)
I will cheer your library. have a nice day 😄 😄

**Comment by wan2land** [comment]
release v1.2.0
