### ISSUE TITLE
BUG: Scroll Offset calculation breaks when placed inside popover, dialog

### ISSUE THREAD

**Issue by akashbagchi** [wan2land/vue-scroll-picker#839]
I tried utilizing the picker component within element plus popovers and dialogs but there seems to be a bug in the Top scroll offset calculation which breaks the scroll and drag functionality of the picker.

https://github.com/wan2land/vue-scroll-picker/assets/72804789/0d6a69d4-32f1-4d1c-a4c4-fe0038f7d753

Clicking on the top and bottom of picker-area seems to update the modelValue without issues, it even highlights the selected Item correctly.

**Comment by wan2land** [comment]
🤔

**Comment by wan2land** [comment]
It seems like there might be a conflict with specific CSS.

Could you provide a simple reproducible code snippet along with the popover library you are using?

**Comment by wan2land** [comment]
It appears that the bug is caused by the component being rendered off-screen and then brought into view. I resolved this issue by using ResizeObserver.

Please refer to the following example:
https://vue-scroll-picker.dist.be/#dialog

**Comment by wan2land** [comment]
I will consider this issue resolved. If you have any further questions, please feel free to create a new issue! Thank you!

**Comment by akashbagchi** [comment]
Thank you for your response! @wan2land 

Sorry for being unavailable to provide snippets last week.
